# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

oarima_test <- function(x, mk = 10L, d = 0L) {
    invisible(.Call(`_blaze_oarima_test`, x, mk, d))
}

stl_test <- function(x, period = 1L, seasonal = 7L) {
    .Call(`_blaze_stl_test`, x, period, seasonal)
}

test_interpol <- function(x, p = 0.5) {
    .Call(`_blaze_test_interpol`, x, p)
}

