# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_seasons <- function(x) {
    .Call(`_blaze_find_seasons`, x)
}

find_period <- function(x) {
    .Call(`_blaze_find_period`, x)
}

draw <- function(x) {
    .Call(`_blaze_draw`, x)
}

