# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_eigen_segment <- function(x, phi_vec) {
    .Call(`_blazearima_test_eigen_segment`, x, phi_vec)
}

